### ISSUE TITLE
空指针问题

### ISSUE THREAD

**Issue by daxiong380380** [ryeyao/stream-lua-nginx-module#1]
Hi Rye
这是我们一个deamo配置文件：
stream {
    upstream backend{
        server 10.120.22.232:50531;
    }
    server {
        listen 1234;
        access_by_lua_block{
        ngx.log(ngx.ERR,"....................")
        }
        proxy_pass backend;
    }
}
在调试过程中，出现了空指针问题，这是gdb的调试信息：
# define ngx_stream_get_module_ctx(s, module) (s)->ctx[module.ctx_index]

Program received signal SIGSEGV, Segmentation fault.
0x000000000054e4b5 in ngx_stream_lua_access_handler (s=0x2b882a912f90) at /home/Nginx/stream-lua-nginx-module-master/src/ngx_stream_lua_accessby.c:41
41 ctx = ngx_stream_get_module_ctx(s, ngx_stream_lua_module);
(gdb) p _s
$6 = {signature = 1297241171, connection = 0x2b882a914260, received = 0, log_handler = 0x0, ctx = 0x0, main_conf = 0x2b882a90ae58, srv_conf = 0x2b882a90bc20, upstream = 0x0}
(gdb) p s->ctx
$7 = (void *_) 0x0
(gdb) 
空指针数组取下标导致coredump了，能帮忙分析下吗？
谢谢哈

**Comment by ryeyao** [comment]
@daxiong380380 这是因为 s->ctx 未初始化。目前要在 stream 里支持这个 access_by_lua\* 的实现，需要给 nginx 的代码打个补丁，具体参考[这个 openresty-bundle 里的 build.sh](https://github.com/ryeyao/openresty-bundle/blob/master/build.sh)。
我会把这个提示补充到 README。

**Comment by daxiong380380** [comment]
@ryeyao 
I'm sorry I am just a fresher, I'd like to known if the openresty-bundle is used to patch specially and how to solve this problem concretely,could you give me a guide, thank you .
(Zhang YiChun said that  we should communicate with English:)

**Comment by ryeyao** [comment]
@daxiong380380 Suppose you are working with openresty-bundle-1.9.7.4 (this is the only tested version), just apply those two patches ( [nginx-allow_override_stream_access_handler.patch](https://github.com/ryeyao/openresty-bundle/blob/master/bundle/nginx-allow_override_stream_access_handler.patch) & [nginx-init_session_before_access_handler.patch](https://github.com/ryeyao/openresty-bundle/blob/master/bundle/nginx-init_session_before_access_handler.patch)) to nginx-1.9.7 like blow:

`cd /path/to/openresty-bundle`

`patch bundle/nginx-1.9.7/src/stream/ngx_stream_handler.c < bundle/nginx-init_session_before_access_handler.patch`

`patch bundle/nginx-1.9.7/src/stream/ngx_stream_access_module.c < bundle/nginx-allow_override_stream_access_handler.patch`

then configure (with this stream-lua-nginx-module included) and compile again. It should work.

**Comment by daxiong380380** [comment]
@ryeyao My openresty version is 1.9.15, does it have that problem

**Comment by ryeyao** [comment]
@daxiong380380 It is an nginx problem, and still not fixed yet AFAIK.

**Comment by daxiong380380** [comment]
@ryeyao 
It still can't work after I applyed the patches, the issue like this:
`nginx: [emerg] "access_by_lua_block" directive is not allowed here in /usr/local/openresty/nginx/conf/nginx.conf:15`
the stream-lua-nginx-module was downloaded at your repository,and my nginx version  is 1.9.15,
Now I don't know how to solve it.

**Comment by daxiong380380** [comment]
@ryeyao  
Thank you for your advise.
Now access_by_lua_block directive can work correctly.
There is an another problem,
the config file is like this:
`access_by_lua_block{

```
            ngx.log(ngx.INFO,"**********TEST access block***********") --first log

            local sock = assert(ngx.req.socket(true))

            sock:settimeout(10000)

            local data = sock:receive()

            ngx.log(ngx.INFO,"**********TEST access block***********") --second log
```

`
the first log can output but the second can not, I wonder that if we cann't get the socket in the access block, but the nginx outputs logs without any error infomations.
(I'd like to get TCP/UDP stream during the access phase, is that right?)

**Comment by ryeyao** [comment]
@daxiong380380 you can retrieve the socket in access phase, but you can not read it (write is ok) because it's not ready to be read. It seems to be a bug in my nginx patches, please open another issue.
